# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# branch whitelist
branches:
  only:
    - develop
    - master

language: objective-c

osx_image: xcode7.2

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
# - set -o pipefail && xcodebuild test -workspace Example/ShakeReport.xcworkspace -scheme ShakeReport-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
